# Usa una imagen base de Node.js
FROM node:20

# Crea el directorio de la aplicación dentro del contenedor
WORKDIR /app

# Copia el package.json y package-lock.json para instalar dependencias
COPY package*.json ./

# Instala las dependencias desde package.json
RUN npm install

# Copia el resto del código
COPY . .

# Expone el puerto que usa la aplicación
EXPOSE 3000

# Comando para correr la aplicación
CMD ["node", "index.js"]
