version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_service2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Stevenpozo12
      POSTGRES_DB: mi_base_de_datos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  product-microservice:
    build: .
    environment:
      DB_USER: postgres
      DB_PASSWORD: Stevenpozo12
      DB_HOST: db
      DB_DATABASE: mi_base_de_datos
      DB_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  pgdata:
